In [5]:
from absenteeism_module import *
pd.read_csv("Absenteeism_new_data.csv")
model = absenteeism_model('linear_reg_model','absenteeism_scaler_object')
model.load_and_clean_data("Absenteeism_new_data.csv")
df_new_obs = model.predicted_outputs()

In [6]:
import pymysql

In [12]:
conn = pymysql.connect(database = 'predicted_outputs', user = 'root', password = 'JCI@20192')

In [13]:
cursor = conn.cursor()

In [15]:

cursor.execute('SELECT * FROM predicted_outputs')

0

## creating the insert query

In [17]:
## INSERT INTO predicted_outputs VALUES 
# (a,b,c,d,...),
# (a1,b1,c1,d1),
# (a2,b2,c2,d2),
# (an,bn,cn,dn) ;

In [19]:
df_new_obs.shape

(40, 13)

In [22]:
df_new_obs.columns.values[2]

'Reason_3'

In [28]:
df_new_obs['Reason_3'][2]

0

In [55]:
insert_query =  'INSERT INTO predicted_outputs VALUES'

In [56]:
for i in range (df_new_obs.shape[0]):
    insert_query += "("
    for j in range (df_new_obs.shape[1]):
        insert_query += str(df_new_obs[df_new_obs.columns.values[j]][i]) + ', '
    insert_query=insert_query[:-2] + '),'    
    
insert_query = insert_query[:-1]+';'
insert_query

'INSERT INTO predicted_outputs VALUES(0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.11042722914632756, 0),(1, 0.0, 0, 0, 6, 361, 28, 27, 0, 1, 4, 0.7859984209599765, 1),(0, 0.0, 0, 1, 6, 155, 34, 25, 0, 2, 0, 0.2508248322615336, 0),(0, 0.0, 0, 1, 6, 179, 40, 22, 1, 2, 0, 0.1648692074979375, 0),(1, 0.0, 0, 0, 6, 155, 34, 25, 0, 2, 0, 0.7438228660677875, 1),(1, 0.0, 0, 0, 6, 225, 28, 24, 0, 1, 2, 0.6763051954804881, 1),(1, 0.0, 0, 0, 6, 118, 46, 25, 0, 2, 0, 0.6124636845686849, 1),(0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.11042722914632756, 0),(0, 0.0, 0, 1, 6, 118, 37, 28, 0, 0, 0, 0.13699017438725253, 0),(1, 0.0, 0, 0, 6, 118, 37, 28, 0, 0, 0, 0.5792352778899191, 1),(0, 0.0, 1, 1, 6, 378, 36, 21, 0, 2, 4, 0.9042715009739399, 1),(0, 0.0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.752872002630706, 1),(0, 0.0, 1, 0, 6, 233, 31, 21, 1, 1, 8, 0.20709179519720491, 0),(0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.11042722914632756, 0),(0, 0.0, 0, 0, 6, 235, 48, 33, 0, 1, 5, 0.05616849773077398, 0),(0, 0.0, 0, 0, 6, 268, 33, 25, 1, 0, 0, 0.18336581886736414, 0),(0, 0.0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.752872002630706, 1),(1, 0.0, 0, 0, 6, 179, 30, 19, 1, 0, 0, 0.5184334485626957, 1),(0, 0.0, 0, 1, 6, 291, 40, 25, 0, 1, 1, 0.31704719525518854, 0),(1, 0.0, 0, 0, 7, 179, 30, 19, 1, 0, 0, 0.5332664040640085, 1),(0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.14417703089395337, 0),(0, 0.0, 1, 1, 7, 233, 31, 21, 1, 1, 8, 0.2948098382638375, 0),(1, 0.0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.5936632958778183, 1),(1, 0.0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.5936632958778183, 1),(0, 0.0, 1, 1, 7, 233, 31, 21, 1, 1, 8, 0.2948098382638375, 0),(0, 0.0, 0, 1, 7, 235, 43, 38, 0, 1, 0, 0.4702969727498762, 0),(0, 0.0, 1, 0, 7, 233, 31, 21, 1, 1, 8, 0.21703148448430504, 0),(1, 0.0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.6397293511132573, 1),(0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.14417703089395337, 0),(1, 0.0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.6397293511132573, 1),(0, 0.0, 1, 1, 7, 189, 33, 25, 0, 2, 2, 0.8573383023536066, 1),(0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.14417703089395337, 0),(0, 0.0, 1, 1, 7, 361, 28, 27, 0, 1, 4, 0.920524568344294, 1),(0, 0.0, 1, 1, 7, 225, 28, 24, 0, 1, 2, 0.8682264557465039, 1),(1, 0.0, 0, 0, 7, 369, 31, 25, 0, 3, 0, 0.9617645046433021, 1),(1, 0.0, 0, 0, 7, 289, 33, 30, 0, 2, 1, 0.8982737168799092, 1),(1, 0.0, 0, 0, 7, 235, 37, 29, 1, 1, 1, 0.712607227695885, 1),(0, 0.0, 0, 0, 7, 118, 40, 34, 0, 1, 8, 0.010507709412106511, 0),(0, 0.0, 0, 0, 7, 231, 39, 35, 0, 2, 2, 0.25161637112212154, 0),(0, 0.0, 0, 0, 7, 179, 53, 25, 0, 1, 1, 0.08576591808911986, 0);'

In [57]:
cursor.execute(insert_query)

40

In [58]:
conn.commit()

In [59]:
conn.close()

In [63]:
# df_new_obs.to_csv("predictiondata_tocsv.csv",index=None)

In [67]:
# df = pd.read_csv("predictiondata_tocsv.csv")
# df
df_new_obs

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Probability,Prediction
0,0,0.0,0,1,6,179,30,19,1,0,0,0.110427,0
1,1,0.0,0,0,6,361,28,27,0,1,4,0.785998,1
2,0,0.0,0,1,6,155,34,25,0,2,0,0.250825,0
3,0,0.0,0,1,6,179,40,22,1,2,0,0.164869,0
4,1,0.0,0,0,6,155,34,25,0,2,0,0.743823,1
5,1,0.0,0,0,6,225,28,24,0,1,2,0.676305,1
6,1,0.0,0,0,6,118,46,25,0,2,0,0.612464,1
7,0,0.0,0,1,6,179,30,19,1,0,0,0.110427,0
8,0,0.0,0,1,6,118,37,28,0,0,0,0.136990,0
9,1,0.0,0,0,6,118,37,28,0,0,0,0.579235,1
10,0,0.0,1,1,6,378,36,21,0,2,4,0.904272,1
11,0,0.0,1,0,6,118,50,31,0,1,0,0.752872,1
12,0,0.0,1,0,6,233,31,21,1,1,8,0.207092,0
13,0,0.0,0,1,6,179,30,19,1,0,0,0.110427,0
14,0,0.0,0,0,6,235,48,33,0,1,5,0.056168,0
15,0,0.0,0,0,6,268,33,25,1,0,0,0.183366,0
16,0,0.0,1,0,6,118,50,31,0,1,0,0.752872,1
17,1,0.0,0,0,6,179,30,19,1,0,0,0.518433,1
18,0,0.0,0,1,6,291,40,25,0,1,1,0.317047,0
19,1,0.0,0,0,7,179,30,19,1,0,0,0.533266,1
20,0,0.0,0,1,7,118,37,28,0,0,0,0.144177,0
21,0,0.0,1,1,7,233,31,21,1,1,8,0.294810,0
22,1,0.0,0,0,7,118,37,28,0,0,0,0.593663,1
23,1,0.0,0,0,7,118,37,28,0,0,0,0.593663,1
24,0,0.0,1,1,7,233,31,21,1,1,8,0.294810,0
25,0,0.0,0,1,7,235,43,38,0,1,0,0.470297,0
26,0,0.0,1,0,7,233,31,21,1,1,8,0.217031,0
27,1,0.0,0,0,7,228,58,22,0,2,1,0.639729,1
28,0,0.0,0,1,7,118,37,28,0,0,0,0.144177,0
29,1,0.0,0,0,7,228,58,22,0,2,1,0.639729,1
30,0,0.0,1,1,7,189,33,25,0,2,2,0.857338,1
31,0,0.0,0,1,7,118,37,28,0,0,0,0.144177,0
32,0,0.0,1,1,7,361,28,27,0,1,4,0.920525,1
33,0,0.0,1,1,7,225,28,24,0,1,2,0.868226,1
34,1,0.0,0,0,7,369,31,25,0,3,0,0.961765,1
35,1,0.0,0,0,7,289,33,30,0,2,1,0.898274,1
36,1,0.0,0,0,7,235,37,29,1,1,1,0.712607,1
37,0,0.0,0,0,7,118,40,34,0,1,8,0.010508,0
38,0,0.0,0,0,7,231,39,35,0,2,2,0.251616,0
39,0,0.0,0,0,7,179,53,25,0,1,1,0.085766,0